name       : libffi
version    : 3.2.1
release    : 10
source     :
    - ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz : d06ebb8e1d9a22d19e38d63fdb83954253f39bedc5d46232a05645685722ca37
license    : MIT
component  : system.base
summary    : Foreign Function Interface library
description: |
    The libffi library provides a portable, high level programming interface to various calling conventions. This allows a programmer to call any function specified by a call interface description at run time.
emul32     : yes
devel      : yes
patterns   :
    - devel : 
        - /usr/share/man
builddeps  :
    - dejagnu-devel
setup      : |
    %patch -p1 < $pkgfiles/includedir.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
