name        : libffi
version     : 3.0.12
release     : 7
source      :
    - ftp://sourceware.org/pub/libffi/libffi-3.0.12.tar.gz : 2ea0db90c2bbcc907c3aefc3f76e9dfc3b35c7a0fb75a4319f5248e0172c1e9e
license     :
    - MIT
summary     : Foreign Function Interface library
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
devel       : yes
patterns    :
    - devel: [/usr/share/man, /usr/share/doc]
description : |
    The libffi library provides a portable, high level programming interface to various calling conventions. This allows a programmer to call any function specified by a call interface description at run time.
setup      : |
    %patch -p1 < $pkgfiles/libffi-3.0.12-includedir-1.patch
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
