name       : libffi
version    : '3.3'
release    : 12
source     :
    - https://github.com/libffi/libffi/releases/download/v3.3/libffi-3.3.tar.gz : 72fba7922703ddfa7a028d513ac15a85c8d54c8d67f55fa5a4802885dc652056
license    : MIT
component  : system.base
summary    : Foreign Function Interface library
description: |
    The libffi library provides a portable, high level programming interface to various calling conventions. This allows a programmer to call any function specified by a call interface description at run time.
emul32     : yes
devel      : yes
patterns   :
    - devel :
        - /usr/share/man
builddeps  :
    - dejagnu-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
